### ISSUE TITLE
Wrong numerical results

### ISSUE THREAD

**Issue by danlkv** [ORNL-QCI/exatn#41] opened 2020-12-01 06:20 UTC
### for matrices generated by numpy

```python
a = np.array([
    [1., 0, 0],
    [0., 1, 1]
])
b = np.array([
    [1., 0, 3, 0],
    [1,  1,  2, 2],
    [-1, 1, -2, 2],
])
exatn.createTensor('C1', [2, 4], 0.)
exatn.createTensor('A1', np.array(a, copy=True)) # copy to prevent exatn from changing the array data
exatn.createTensor('B1', np.array(b, copy=True))
exatn.evaluateTensorNetwork('test', 'C1(a, c) = A1(a, b) * B1(b, c)')

c1_exatn = exatn.getLocalTensor('C1')

assert np.allclose(c1_exatn, np.dot(a, b)) # raises assertion error

"""
The result should be
[[1 0 3 0],
 [0 2 0 4]]

Easily checkable by hand for above example matrices
"""
```

The data received back from exatn by `exatn.getLocalTensor(name)` match the original array.

### For matrices generated by `exatn.initTensorRnd`
```python
exatn.createTensor('Xr', [2, 3], 0)
exatn.createTensor('Yr', [3, 4], 0)
exatn.initTensorRnd('Xr')
exatn.initTensorRnd('Yr')

xr = exatn.getTensorData('Xr')
yr = exatn.getTensorData('Yr')
zr = np.dot(xr, yr)

exatn.createTensor('Zr', [2, 4], 0)
exatn.evaluateTensorNetwork('rnd', 'Zr(a, b) = Xr(a, c) * Yr(c, b)')
zr_exatn = exatn.getTensorData('Zr')

assert np.allclose(zr_exatn, zr), "Results do not match!" #Raises as well
```

### What is going on

Having found this issue, I tried to understand what are the numbers that exatn returns - they were correct for scalar product of vectors and somewhat correct for matrix-vector multiplication. 
I noticed that for square matrices, when doing `A*B` exatn returns `B*A`. 
However, it turns out that it's more complicated - _rectangular_ matrices do not result in index mismatch, but produce completely different numbers.

Turns out exatn re-arranges data in an interesting way - it applies a function `S` to each input, and `S^-1` to output as defined below.

Continuing from the previous code snippet:
```python
def S(x):
    """ Reshape to reverse-ordered shape,
     then transpose to match the original shape
    """
    x = x.reshape(*reversed(x.shape))
    x = x.transpose() # reverses order of axis by default
    return x

def inv_S(x):
    """ Inverse of S. """
    x = x.transpose() # reverses order of axis by default
    x = x.reshape(*reversed(x.shape))
    return x

adj_zr = inv_S(np.dot(S(xr), S(yr)))


assert np.allclose(zr_exatn, adj_zr) # Will NOT raise!
```

```python
>>> S(np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
]))
array([[1, 3, 5, 7],
       [2, 4, 6, 8]])
```
The same issue is observed when contracting larger tensor networks.

```python
x, y, z = [np.random.randn(*sh) for sh in [
    (2, 3),
    (3, 2, 2),
    (2, 2, 2)
]] # generate some random data
# %%
exatn.createTensor('X', np.array(x, copy=True))
exatn.createTensor('Y', np.array(y, copy=True))
exatn.createTensor('Z', np.array(z, copy=True))

tn = exatn.TensorNetwork('test2')
tn.appendTensor(1, 'X')
tn.appendTensor(2, 'Y', [(1, 0)])
tn.appendTensor(3, 'Z', [(1, 0), (2,1)])
tn.printIt()

# This is equivalent to exatn.evaluateTensorNetwork('test2', 'F0(a,b) = X(a,c) * Y(c,d,e) * Z(d,e,b)')
exatn.evaluate(tn)
result = tn.getTensor(0)
result_name = result.getName()
result_data = exatn.getTensorData(result_name)

### Compare results to einsum
einsum_data = np.einsum('ij,jkl,klm->im', x, y, z)
assert np.allclose(einsum_data, result_data) # Raises

### Fix numerics with reshape-transform

einsum_data_adj = inv_S(np.einsum('ij,jkl,klm->im', S(x), S(y), S(z)))

assert np.allclose(einsum_data_adj, result_data) # Does not raise!
```

Note that `S(A)*S(B)` produces completely different numbers from `A*B` - it is not just an issue of indexing/shaping convention. To obtain `A*B` from exatn one has to perform `S(S^-1(A)*S^-1(B))`. 

## 2. Tests are not robust
All the tests and examples in python folder use tensors that are fixed poins for `S`. They are either constant-valued (simple.py, hamiltonian.py...) or diagonal and square (quantum_circuit_network.py, large_circuit.py...) and hence do not change when reshaped+transposed.

I looked through C++ tests in `src/exatn/tests/NumServerTester.cpp` and it looks like the same problem is there as well, for example on line 1332 again all tensors are square and diagonal.

What implications does this have on cache efficiency?

Exatn was built from latest devel branch (commit 7c722c5eefd3)
More detailed examples at https://github.com/danlkv/QTensor/blob/dev/scratchpad/exatn/exatn_demo.py

**Comment by DmitryLyakh** [comment] 2020-12-01 16:31
I think the problem is that you are using row-major storage in your numpy arrays whereas ExaTN assumes the column-major storage layout for all its tensors. You can either try using column-major storage in your numpy arrays or change the initialization layout (rows <--> columns). Ideally the Python interface should figure this out automatically, but we have not implemented that yet. Unfortunately we do not have enough man power to support the Python interface well. In any case, there should be no issues once you adhere to the column-major storage.

**Comment by danlkv** [comment] 2020-12-01 17:12
Yes, looks like passing `order='F'` to array constructor produces correct results. Why does then the `exatn.initTensorRnd`-generated tensors not match, they have nothing to do with numpy?

**Comment by DmitryLyakh** [comment] 2020-12-01 17:29
I think it might be because the returned NumPy arrays are not marked column-major, which would be a bug. Need to check. Are you planning on using ExaTN Python interface in production?

**Comment by danlkv** [comment] 2020-12-01 17:45
Yes, most of our code is written in python, but we probably won't need exatn-generated arrays. Passing with order=F produces correct numbers, but in a mixed order. The output array is again row-major, but with column-major data, which could be a problem if we pass arrays back to exatn.

**Comment by DmitryLyakh** [comment] 2020-12-01 18:12
Ok, that's what I suspected, the returned tensor copies are not marked as column-major. This should be fixed in the ExaTN Python interface. But this is a minor issue. My main concern is that the current ExaTN Python bindings are synchronous and, as a consequence, low-performing, so not very useful for a production HPC version. ExaTN is a C++ library, all the performance is only guaranteed in the C++ API, not Python. As I said, currently we do not have anyone supporting the Python interface, which otherwise would make it possible to provide a better performing Python bindings. Is there a possibility for you to leverage the C++ API instead?

**Comment by danlkv** [comment] 2020-12-01 18:38
We will need to write our own bindings to use C++ API, so it effectively would mean modifying existing bindings. Shouldn't we be able just call async versions of c++ methods in the bindings file?

**Comment by DmitryLyakh** [comment] 2020-12-01 19:02
Technically, yes, plus proper synchronization. ExaTN is fully asynchronous, so every time you request a copy of a tensor or initialize it with external data, you will need to impose synchronization. Also, Python global lock needs to be taken into account.

**Closed** 2021-02-03 17:45 UTC
